# ============================================================
# OceanTracerPINN Inference Configuration
# ============================================================

inference:
  name: OceanTracerPINN
  seed: 42
  nc_path: "DavisStrait_adjusted_v_fulldepth.nc"
  output_dir: "/gws/ssde/j25a/nemo/vol4/thopri/OceanTracerPINN/outputs/inference_davis"
  mc_samples: 100
  checkpoint: "/gws/ssde/j25a/nemo/vol4/thopri/OceanTracerPINN/outputs/oxygen18/experiment2/pinn_oxygen18.pt"
  time_dim: "time"
  dep_dim: "depth"
  lat_dim: "lat"
  lon_dim: "lon"
  v_var: "v"
  u_var: null
  salt_var: "SA"
  temp_var: "CT"
  conservativeT: true
  absoluteS: true
